version: '3.3'
services:
  db:
    image: mysql:latest
    networks:
      - bankuish
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_ROOT_PASSWORD: $DB_USER_PASSWORD
      MYSQL_TCP_PORT: $DB_PORT
    expose:
      - '$DB_PORT'
    volumes:
      - ./mysql:/var/lib/mysql
  nestjs-api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - DB_HOST=mysql
    ports:
      - '$PORT:3000'
    depends_on:
      - db
    networks:
      - bankuish
    links:
      - db:mysql
    command: './wait-for-it.sh mysql:$DB_PORT -t 300 -- node dist/main.js'
networks:
  bankuish:
    driver: bridge
